env: "local" # local, dev, prod
storage_link:
  sql_driver: "postgres"
  sql_user: "postgres"
  sql_password: "Vfrc12232"
  sql_host: "172.23.208.1"
  sql_port: "5433"
  sql_dbname: "url-shortener"
  sql_sslmode: "disable"
http_server:
  address: "localhost:5433"
  timeout: "4s"
  idle_timeout: "60s"